name: fitness
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.6.0
  firebase_auth: ^3.0.1
  google_sign_in: ^5.0.5
  #flutter_facebook_auth: ^3.5.0
  firebase_analytics: ^9.0.2
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  flutter_native_splash: ^1.2.3
  google_fonts: ^2.1.0
  path_provider:
  hive_flutter: ^1.1.0
  hive: ^2.0.4
  get: ^4.3.8
  flutter_staggered_grid_view: ^0.4.0
  fancy_bar: ^2.0.0
  logger: ^1.0.0
  flutter_launcher_icons: ^0.9.1
  lottie: ^1.1.0
  just_audio: ^0.9.11
  audio_session: ^0.1.6
  audio_service: ^0.18.0
  just_audio_background: ^0.0.1-beta.1
  carousel_slider: ^4.0.0
  table_calendar: ^3.0.2
  shared_preferences: ^2.0.8
  cached_network_image: ^3.1.0
  flutter_cache_manager: ^3.1.3
  video_player: ^2.2.6
  card_swiper: ^1.0.4
  circular_countdown_timer: ^0.2.0
  fl_chart: ^0.40.2
  objectbox: ^1.3.0
  percent_indicator: ^3.4.0
  syncfusion_flutter_datepicker: ^19.3.57
  flutter_svg: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  objectbox_generator: any
  build_runner:
 # jitsi_meet: ^4.0.0
 # just_audio_platform_interface: ^4.0.0
dependency_overrides:
  #audio_service: ^0.18.0-beta.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/json/
    - assets/images/error/
    - assets/images/focus_area/
    - assets/images/food/
flutter_native_splash:
  color: "#ffffff"
  #background_image: "assets/images/person_exercising.jpg"
  image: "assets/images/person_exercising.jpg"
  color_dark: "#ffffff"
  #background_image_dark: "assets/images/fitness_logo.jpg"
  image_dark: "assets/images/fitness_logo.jpg"
  android: true
  ios: true
  web: true
  #android12: true

  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center

  # To hide the notification bar, use the fullscreen parameter.  Has no affect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'
